### ISSUE TITLE
cat counter

### ISSUE THREAD

**Issue by J-Weeks** [ga-wdi-boston/ruby-objects-class-methods#7]
Class variables?

**Comment by jrhorn424** [comment]
Did you present class variables? I'd like to avoid that in the future.

I was certain this same example in another repository did not use them.

**Comment by J-Weeks** [comment]
Remove the demo from this, @gaand thoughts on another possible demo or example that uses class methods but not class variables?

**Comment by J-Weeks** [comment]
custom getter/setter implementation added in commit cd753b5
